spring:
  datasource:
    url: "jdbc:mysql://118.70.117.39:3306/category?createDatabaseIfNotExist=true&autoReconnect=true&testOnBorrow=true&useSSL=false&interactiveClient=true&noAccessToProcedureBodies=true&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: bitsco
    password: Bitsco@2021
  #Redis configurations
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-idle: 8
        max-wait: -1
        min-idle: 0
        timeout: 0
